### ISSUE TITLE
returning `Events` from a function

### ISSUE THREAD

**Issue by danieleades** [pulldown-cmark/pulldown-cmark#625]
I'm using this library in an MdBook extension ([mdbook-d2](https://github.com/danieleades/mdbook-d2))

It's working a treat, but there's one rough edge. I'd like to return some `Events` from a function, something like the following-

```rust
let image_path = "path/to/image/file.svg";
fn generate_inline_img(path: &str) -> Vec<Event<'_>> {
    let snippet = format!("![]({path})");
    Parser::new(&snippet).collect()
}
let _events = generate_inline_img(image_path);
```

this doesn't work, since the `Parser` is carrying a reference to the local `snippet` variable.
Basically i'd like a way to opt out of the zero-copy implementation for cases like this. I *think* this could be achieved if the `Parser` accepted an `impl Into<CowStr<'input>>` instead of `&'input str`.

My current workaround is to manually construct the snippet like so-

*from [mdbook-d2](https://github.com/danieleades/mdbook-d2)*
```rust
    pub fn render(&self, ctx: RenderContext, content: &str) -> Vec<Event<'static>> {
        fs::create_dir_all(Path::new("src").join(self.output_dir())).unwrap();

        self.run_command(&ctx, content);

        let depth = ctx.path.ancestors().count() - 1;
        let rel_path: PathBuf = std::iter::repeat(Path::new(".."))
            .take(depth)
            .collect::<PathBuf>()
            .join(self.relative_file_path(&ctx));

        vec![
            Event::Start(Tag::Image(
                LinkType::Inline,
                rel_path.to_string_lossy().to_string().into(),
                CowStr::Borrowed(""),
            )),
            Event::End(Tag::Image(
                LinkType::Inline,
                rel_path.to_string_lossy().to_string().into(),
                CowStr::Borrowed(""),
            )),
        ]
    }
```

or am I perhaps taking the wrong approach entirely in this preprocessor?

**Comment by Atreyagaurav** [comment]
This is something I have come across too. I think it makes sense to accept `CowStr` instead of `&str` so that we can use all `Owned` variety of the `CowStr` when we need `' static`. 

I have a table in Markdown that I want to generate and insert into the tree. 

Code is something like:
```rust
let events = parser.try_fold(vec![], |mut acc, ref e| -> anyhow::Result<Vec<Event<'_>>> {
// Extract Code Block, run the code and get the table output into a String
// Use that String to generate a markdown table [CAUSE of PROBLEM]
// append that to `acc` [ACTUAL PROBLEM]
}
Ok(cmark(events.iter(), &mut buf).map(|_| buf)?)
```

So here, since the `String` used to for the new `Parser` inside the loop gets dropped at the end, I cannot append it to the `acc`. If I had `Event<'static>` with Owned variety of Strings, it should be fine.

I have tried various methods to try to get the borrow checker to be satisfied, but none of them work.

For reference, this is what I currently have:
![image](https://github.com/user-attachments/assets/a0ef7323-2ab2-4db7-9e4c-206341bde6ba)

Instead of the text block of the table on the bottom, I want to parse that table and add that to the original.

**Comment by ollpu** [comment]
One way to accomplish this (too) is with an iterator adapter that clones all CowStrs in the Events into `CowStr<'static>`. I suspect implementing this inside the parser itself wouldn't be meaningfully more performant.

**Comment by Atreyagaurav** [comment]
Yeah, Currently the workaround I'm working towards is just converting all the possible events.

Here is the function I'm using to convert all the `Event`s to static (Note: I'm working with `0.10.3` because of `pulldown-cmark-to-cmark`:
```rust
fn event_to_static(event: Event<'_>) -> Event<'static> {
    match event {
        // ones with lifetime
        Event::Start(t) => Event::Start(tag_to_static(t)),
        Event::Text(t) => Event::Text(t.to_string().into()),
        Event::Code(t) => Event::Code(t.to_string().into()),
        Event::Html(t) => Event::Html(t.to_string().into()),
        Event::InlineHtml(t) => Event::InlineHtml(t.to_string().into()),
        Event::FootnoteReference(t) => Event::FootnoteReference(t.to_string().into()),
        // without lifetime; you can't do e => e, as enum has lifetime
        Event::End(t) => Event::End(t),
        Event::SoftBreak => Event::SoftBreak,
        Event::HardBreak => Event::HardBreak,
        Event::Rule => Event::Rule,
        Event::TaskListMarker(b) => Event::TaskListMarker(b),
    }
}
```
I'll have to recursively convert any variants with lifetime that is not `CowStr` with other functions like `tag_to_static` here. So it is a lot of work.

**Comment by Atreyagaurav** [comment]
I think simply adding
[std](https://doc.rust-lang.org/std/index.html)::[borrow](https://doc.rust-lang.org/std/borrow/index.html)::[ToOwned](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html) implementation to the `Event` type that converts any internal `CowStr::Borrowed` to `CowStr::Owned` would be nice.

**Comment by ollpu** [comment]
Yeah, that's a good idea

**Comment by Atreyagaurav** [comment]
I can make a pull request if that is ok. I already have the match statements for my functions with all event's conversions.
