### ISSUE TITLE
construct Parser from Events, or the ability to push and pop to and from the iterator

### ISSUE THREAD

**Issue by atgumx** [pulldown-cmark/pulldown-cmark#860]
Is there a way to reconstruct Parser from Events? Like directly manipulate and add nodes to the AST. And how easy would it be to implement it?

I'm trying to write a piece of code that adds some kind of TOC to a markdown file and the only way I can think of currently is to just filter out the old list from the String and concatenate the new one.

**Comment by Martin1887** [comment]
There is not a direct way of doing that, especially because the parser is incremental and to do that the whole document should be parsed first.

One manner of doing that is collecting the things you want to change in a loop until exhausting the iterator and after that applying the modifications to the document you want using the ranges.

Another manner would be creating another MD from the events and then creating another parser for the new MD.

To manipulate the AST it is easier to use https://github.com/wooorm/markdown-rs or https://github.com/kivikakk/comrak.

**Comment by atgumx** [comment]
I've seen both packages but went with pulldown-cmark since it's the most popular. I think I'll close this issue and watch if this ever gets into the scope of the project.

Thanks you :)
