### ISSUE TITLE
Weird code block behavior

### ISSUE THREAD

**Issue by DasLixou** [pulldown-cmark/pulldown-cmark#897]
I have this string:
```rs
r##" ```test 
            whas soll das?!
            ```"##
```
and when I render it to html, the trailing `\`\`\`` also get rendered. When it's all on one line, it doesn't.

I also got one where everything renders (also the trailing and the language) but still in a codeblock, and another one where the code block doesn't even get `<pre><code>` and is just there as plain text, but I can't share the input of that

**Comment by ehuss** [comment]
I believe this is working correctly. The closing code fence may only be indented up to three spaces. See [Fenced code blocks](https://spec.commonmark.org/0.31.2/#fenced-code-blocks) for more details.

**Comment by DasLixou** [comment]
Oh I see thanks. I hope i can get an example together to the phenomenon of not making the code block.

**Comment by DasLixou** [comment]
Ok I got another sample to reprod and I think there it should make a code block but doesn't: 
```rs
"/// ```\n\n/// code blocks!\n\n/// ```\n"
```

**Comment by ehuss** [comment]
Can you say why you think there should be a code block? The [fence](https://spec.commonmark.org/0.31.2/#fenced-code-blocks) can only be preceded by up to three spaces. It looks like you have forward slashes in front of them, which aren't part of the commonmark spec, and I think would need to be a [container block](https://spec.commonmark.org/0.31.2/#container-blocks) in order to allow code blocks within them.

**Comment by DasLixou** [comment]
Because this https://spec.commonmark.org/dingus/?text=%2F%2F%2F%20%60%60%60%0A%2F%2F%2F%20test%0A%2F%2F%2F%20%60%60%60 works

**Comment by ehuss** [comment]
That looks to be different than what you posted. That only contains single newlines, and thus the triple backticks are treated as [inline code spans](https://spec.commonmark.org/0.31.2/#code-spans). When there are double-newlines as in the example above, it breaks the paragraph, causing the span to stop.
