### ISSUE TITLE
Table generation

### ISSUE THREAD

**Issue by FedericoPonzi** [pulldown-cmark/pulldown-cmark#970]
Hello,
I'm trying to generate tables out of markdown. I know I need to use GCM as it's not part of commonmark. This is the relevant part of the code:
```
pub(crate) fn compile_markdown_to_html(markdown_input: &str) -> String {
    use pulldown_cmark::{html, Options, Parser};
    let mut options = Options::empty();
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_HEADING_ATTRIBUTES);
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_GFM);

    let parser = Parser::new_ext(markdown_input, options);

    // Write to String buffer.
    let mut html_output = String::new();
    html::push_html(&mut html_output, parser);
    html_output
}
```
This is the input:
```
| foo | bar |
| --- | --- |
| baz | bim |
```
This is the output:
```
<p>| foo | bar |</p>
<p>| --- | --- |</p>
<p>| baz | bim |</p>
```

Am I missing anything? The full code can be found here: https://github.com/FedericoPonzi/genereto/blob/main/src/parser.rs#L78

I'm also curious to know: if tables are part of GCM, what's the TABLE option used for? Do I really need both? I tried to comment each of them but couldn't get the expected html table

**Comment by ollpu** [comment]
I can't seem to replicate your output.

It looks like a preprocessing step in your code is duplicating newlines:

```rust
        if line.trim().starts_with("$GENERETO{") {
            // ...
        } else if line.contains("$GENERETO{") {
            // ...
        } else {
            // This is the normal case, it appends a newline
            line_new += "\n"; // no comments.
        }
        page_content_new.push_str(&format!("{line_new}\n")); // Second newline added here
```

Only the `ENABLE_TABLES` option affects the rendering of tables. I agree `ENABLE_GFM` is a little confusing. Currently it only controls Blockquote Tags. It was my idea to collect miscellaneous GFM features under the flag, since there will likely be more random features added in the future. But maybe it should've been called `ENABLE_GFM_MISC`.

**Comment by FedericoPonzi** [comment]
You're awesome! Thanks for spotting the bug and for the library!
